server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: asistenciaService
          uri: lb://asistencia-service
          predicates:
            - Path=/asistencia/**
        - id: categoriaService
          uri: lb://categoria-service
          predicates:
            - Path=/categorias/**
        - id: empleadosService
          uri: lb://empleados-service
          predicates:
            - Path=/empleado/**
        - id: horasExtrasService
          uri: lb://horasextras-service
          predicates:
            - Path=/horasExtras/**
        - id: justificativoService
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**
        - id: planillaService
          uri: lb://planilla-service
          predicates:
            - Path=/planilla/**
