server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: asistenciaService
          uri: lb://asistenciaService
          predicates:
            - Path=/asistencia/**
        - id: categoriaService
          uri: lb://categoriaService
          predicates:
            - Path=/categorias/**
        - id: empleadosService
          uri: lb://empleadosService
          predicates:
            - Path=/empleado/**
        - id: horasExtrasService
          uri: lb://horasExtrasService
          predicates:
            - Path=/horasExtras/**
        - id: justificativoService
          uri: lb://justificativoService
          predicates:
            - Path=/justificativo/**
        - id: planillaService
          uri: lb://planillaService
          predicates:
            - Path=/planilla/**